AllCops:
  TargetRubyVersion: 2.6
  Include:
    - "./Rakefile"
    - "instapaper.gemspec"
    - "lib/**/*.rb"
    - "spec/**/*.rb"
  DisplayCopNames: true
  SuggestExtensions: false
  NewCops: enable

Layout/LineLength:
  AllowURI: true
  Enabled: false

Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space

Metrics/BlockNesting:
  Max: 2

Metrics/MethodLength:
  CountComments: false
  Max: 10

Metrics/ParameterLists:
  Max: 4
  CountKeywordArgs: true

Metrics/BlockLength:
  Enabled: false

Style/CollectionMethods:
  PreferredMethods:
    map: "collect"
    reduce: "inject"
    find: "detect"
    find_all: "select"

Style/Documentation:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Style/MutableConstant:
  Enabled: false

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: "comma"

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: "comma"

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: "comma"
